server:
  port: ${PORT:8080}

spring:
  application:
    name: registration

  datasource:
    url: jdbc:sqlite:registration.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true

cricketApi:
  key: "2e6b39d6bcmsh2a39f0f3a2bbef0p168d12jsn817896aaeb8a"
  host: 'cricket-api-free-data.p.rapidapi.com'