server:
  port: ${PORT:8080}

spring:
  application:
    name: registration

  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}:${MYSQLDATABASE}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
    show-sql: true

cricketApi:
  key: "2e6b39d6bcmsh2a39f0f3a2bbef0p168d12jsn817896aaeb8a"
  host: 'cricket-api-free-data.p.rapidapi.com'